// === Kura Reception — seed data ===

// === Blank-state factory (dev tester) ===
// Returns a patient stripped to first-arrival, no PII captured yet.
// Preserves id/queueNumber/avatarColor so the row stays in the queue.
export function blankPatient(id = "p-blank", queueNumber = "Q-000", avatarColor = "av-blue") {
  return {
    id, queueNumber, avatarColor,
    name: "", initials: "—",
    gender: "—", sexAtBirth: "",
    age: 0, dob: "",
    arrivedAt: "just now",
    arrivedRaw: "Today, just now",
    status: { tone: "info", label: "Awaiting check-in" },
    visitReason: [],
    language: "Khmer",          // default Khmer for blank/manual flow
    countryCode: "+855",
    phoneNumber: "",
    mobile: "",
    telegramHandle: "",
    telegramVerified: false,
    commMethod: "sms",
    otpVerified: false,
    pwaSentAt: null,
    idScanned: false,
    idNumber: "",
    payer: "direct",
    documents: { id: "pending", consent: "pending", insurance: "pending", receipt: "pending" },
    pwaProgress: 0,
    pwaLog: [],
    services: [],
    cart: {
      items: [],
      promos: {},
      splits: null,
      ccy: "USD",
      payment: { method: null, status: "idle", tendered: "" },
      pregnancyConsent: null,
    },
    visitDetails: {
      chiefComplaint: "", medicalHistory: "", medications: "",
      allergies: "", notes: "",
    },
    visitDetailsAuthors: {},
    labTests: [],
    insurance: [],
    priorResults: [],
    teleconsult: { status: "notBooked", slot: null, by: null },
    handoff: 0,
    handoffStates: ["in-progress", "pending", "pending", "pending"],
    identity: { verified: false },
    manualEntry: false,
  };
}

export const initialPatients = [
  {
    id: "p1",
    name: "Maya Tran",
    gender: "Female",
    sexAtBirth: "Female",
    age: 28,
    initials: "MT",
    avatarColor: "av-blue",
    arrivedAt: "09:12 AM",
    queueNumber: "Q-042",
    status: { tone: "info", label: "PWA sent" },
    visitReason: ["General check-up"],
    language: "English",
    countryCode: "+855",
    phoneNumber: "12 345 678",
    mobile: "+855 12 345 678",
    dob: "1996-02-14",
    telegramHandle: "t.me/mayatran",
    telegramVerified: true,
    commMethod: "telegram",
    otpVerified: true,
    pwaSentAt: "09:12 AM",
    idScanned: true,
    idNumber: "012345678",
    payer: "direct",
    documents: { id: "ok", consent: "ok", insurance: "pending", receipt: "pending" },
    pwaProgress: 62,
    pwaLog: [
      { type: "sent",      text: "Link sent by SMS",         time: "09:12 AM", state: "ok" },
      { type: "verified",  text: "OTP verified",             time: "09:13 AM", state: "ok" },
      { type: "pending",   text: "Medical history pending",  time: "62% complete", state: "pending" },
    ],
    services: [
      { name: "CBC",            payer: "Direct Pay", status: "draft", amount: 6 },
      { name: "Glucose Fasting",payer: "Direct Pay", status: "draft", amount: 3 },
      { name: "Vitamin D",      payer: "Direct Pay", status: "draft", amount: 25 },
      { name: "X-ray Chest",    payer: "Direct Pay", status: "draft", amount: 15 },
    ],
    cart: {
      items: [
        { id: "visit-gp", kind: "visit", name: "GP consultation (visit fee)", price: 15, qty: 1, payer: "direct", status: "pending", auto: true },
        { id: "cbc", kind: "lab", name: "Complete Blood Count (CBC)", price: 8, qty: 1, payer: "direct", status: "pending" },
        { id: "glucose", kind: "lab", name: "Blood Glucose (Fasting)", price: 5, qty: 1, payer: "direct", status: "pending", fasting: true },
        { id: "xray-chest", kind: "imaging", name: "X-ray — Chest", price: 15, qty: 1, payer: "direct", status: "pending" },
      ],
      promos: {},
      splits: null,
      ccy: "USD",
      payment: { method: null, status: "idle", tendered: "" },
      pregnancyConsent: null,
    },
    visitDetails: {
      chiefComplaint: "Headache and mild fever for 3 days",
      medicalHistory: "Hypertension (controlled), no surgeries",
      medications: "Lisinopril 10mg daily",
      allergies: "Penicillin",
      notes: "",
    },
    labTests: [
      { id: "cbc",     name: "Complete Blood Count (CBC)", price: 8, status: "in-progress" },
      { id: "glucose", name: "Blood Glucose (Fasting)",    price: 5, status: "pending" },
    ],
    insurance: [],
    visitDetailsAuthors: {
      chiefComplaint: "patient",
      medicalHistory: "patient",
      medications: "patient",
      allergies: "patient",
    },
    priorResults: [
      { id: "pr-1", testId: "lipid", testName: "Lipid Panel", visitDate: "2026-01-14", status: "complete", price: 12, sensitive: true },
      { id: "pr-2", testId: "hba1c", testName: "HbA1c (Diabetes)", visitDate: "2026-01-14", status: "complete", price: 11, sensitive: true },
      { id: "pr-3", testId: "cbc", testName: "Complete Blood Count (CBC)", visitDate: "2025-10-04", status: "complete", price: 8, sensitive: false },
    ],
    teleconsult: { status: "booked", slot: { id: "tom_am", hint: "Tomorrow · 09:00–09:30" }, by: "nurse", bookedAt: "2026-04-29T08:30:00Z" },
    handoff: 1,
    handoffStates: ["new","in-progress","pending","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:12 AM",
  },
  {
    id: "p2",
    name: "Bao Nguyen",
    gender: "Male",
    sexAtBirth: "Male",
    age: 35,
    initials: "BN",
    avatarColor: "av-green",
    arrivedAt: "09:05 AM",
    queueNumber: "Q-041",
    status: { tone: "warn", label: "Needs insurance" },
    visitReason: ["Annual physical"],
    language: "Vietnamese",
    countryCode: "+84",
    phoneNumber: "933 222 110",
    mobile: "+84 933 222 110",
    dob: "1989-06-03",
    telegramHandle: "",
    commMethod: "sms",
    otpVerified: true,
    pwaSentAt: "09:05 AM",
    idScanned: true,
    idNumber: "445566778",
    payer: "insurance",
    documents: { id: "ok", consent: "ok", insurance: "pending", receipt: "pending" },
    pwaProgress: 80,
    pwaLog: [
      { type: "sent",     text: "Link sent by SMS",        time: "09:05 AM", state: "ok" },
      { type: "verified", text: "OTP verified",            time: "09:06 AM", state: "ok" },
      { type: "warn",     text: "Insurance card not uploaded", time: "Awaiting", state: "warn" },
    ],
    services: [
      { name: "Lipid Panel", payer: "Insurance",  status: "pending", amount: 12 },
      { name: "ECG",         payer: "Insurance",  status: "pending", amount: 22 },
    ],
    visitDetails: {
      chiefComplaint: "Routine annual physical",
      medicalHistory: "",
      medications: "",
      allergies: "None known",
      notes: "",
    },
    labTests: [
      { id: "lipid", name: "Lipid Panel", price: 12, status: "pending" },
    ],
    insurance: [
      { id: "ins-p2", provider: "Forte Insurance", policyNumber: "FT-00123456", memberName: "Bao Nguyen", memberId: "M-7788991", expiry: "12/2026", coverage: "Outpatient", cardAttached: false },
    ],
    visitDetailsAuthors: {
      chiefComplaint: "patient",
      allergies: "patient",
    },
    priorResults: [
      { id: "pr-b1", testId: "lipid", testName: "Lipid Panel", visitDate: "2025-12-02", status: "complete", price: 12, sensitive: true },
      { id: "pr-b2", testId: "ecg-12", testName: "ECG — 12 lead", visitDate: "2025-12-02", status: "complete", price: 22, sensitive: false },
    ],
    handoff: 1,
    handoffStates: ["done","in-progress","pending","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:05 AM",
  },
  {
    id: "p3",
    name: "Pierre Tison",
    gender: "Male",
    sexAtBirth: "Male",
    age: 31,
    initials: "PT",
    avatarColor: "av-amber",
    arrivedAt: "08:58 AM",
    queueNumber: "Q-040",
    status: { tone: "success", label: "Ready for nurse" },
    visitReason: ["Follow-up"],
    language: "English",
    countryCode: "+855",
    phoneNumber: "77 555 244",
    mobile: "+855 77 555 244",
    dob: "1993-11-22",
    telegramHandle: "t.me/pierret",
    telegramVerified: true,
    commMethod: "telegram",
    otpVerified: true,
    pwaSentAt: "08:58 AM",
    idScanned: true,
    idNumber: "998877665",
    payer: "corporate",
    documents: { id: "ok", consent: "ok", insurance: "ok", receipt: "ok" },
    pwaProgress: 100,
    pwaLog: [
      { type: "sent",     text: "Link sent by SMS",      time: "08:58 AM", state: "ok" },
      { type: "verified", text: "OTP verified",          time: "08:59 AM", state: "ok" },
      { type: "ok",       text: "Medical history complete", time: "09:04 AM", state: "ok" },
    ],
    services: [
      { name: "Blood Pressure",  payer: "Corporate", status: "ready", amount: 0 },
      { name: "Vision Test",     payer: "Corporate", status: "ready", amount: 0 },
    ],
    visitDetails: {
      chiefComplaint: "Follow-up after lipid results last visit",
      medicalHistory: "Borderline cholesterol",
      medications: "None",
      allergies: "None",
      notes: "Patient reports diet changes are working.",
    },
    labTests: [
      { id: "hba1c", name: "HbA1c (Diabetes)", price: 11, status: "complete" },
      { id: "lipid", name: "Lipid Panel",      price: 12, status: "complete" },
    ],
    insurance: [],
    handoff: 2,
    handoffStates: ["done","done","in-progress","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 08:58 AM",
  },
  {
    id: "p4",
    name: "An Le",
    gender: "Female",
    sexAtBirth: "Female",
    age: 42,
    initials: "AL",
    avatarColor: "av-pink",
    arrivedAt: "08:45 AM",
    queueNumber: "Q-039",
    status: { tone: "danger", label: "Missing consent" },
    visitReason: ["X-ray follow-up"],
    language: "Vietnamese",
    countryCode: "+855",
    phoneNumber: "88 102 909",
    mobile: "+855 88 102 909",
    dob: "1982-04-30",
    telegramHandle: "",
    commMethod: "sms",
    otpVerified: false,
    idScanned: true,
    idNumber: "112233445",
    payer: "direct",
    documents: { id: "ok", consent: "pending", insurance: "pending", receipt: "pending" },
    pwaProgress: 45,
    pwaLog: [
      { type: "sent",     text: "Link sent by SMS",  time: "08:45 AM", state: "ok" },
      { type: "verified", text: "OTP verified",      time: "08:46 AM", state: "ok" },
      { type: "danger",   text: "Consent declined — needs counter signature", time: "Blocking", state: "danger" },
    ],
    services: [
      { name: "X-ray Lumbar", payer: "Direct Pay", status: "blocked", amount: 18 },
    ],
    visitDetails: {
      chiefComplaint: "",
      medicalHistory: "",
      medications: "",
      allergies: "",
      notes: "",
    },
    labTests: [],
    insurance: [],
    handoff: 0,
    handoffStates: ["in-progress","blocked","pending","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 08:45 AM",
    exception: "consent",
  },
  {
    id: "p5",
    name: "Sokha Pich",
    gender: "Female",
    sexAtBirth: "Female",
    age: 54,
    initials: "SP",
    avatarColor: "av-purple",
    arrivedAt: "09:22 AM",
    queueNumber: "Q-043",
    status: { tone: "success", label: "Checked in" },
    checkedInAt: "2026-05-02T02:28:00Z",
    visitReason: ["Diabetes follow-up", "HbA1c"],
    language: "Khmer",
    countryCode: "+855",
    phoneNumber: "16 904 221",
    mobile: "+855 16 904 221",
    dob: "1972-09-18",
    telegramHandle: "t.me/sokhapich",
    telegramVerified: true,
    commMethod: "telegram",
    otpVerified: true,
    pwaSentAt: "09:20 AM",
    idScanned: true,
    idNumber: "550091882",
    payer: "direct",
    insuranceAcked: true,
    documents: { id: "ok", consent: "ok", insurance: "pending", receipt: "ok" },
    pwaProgress: 100,
    pwaLog: [
      { type: "sent", text: "Link sent by Telegram", time: "09:20 AM", state: "ok" },
      { type: "verified", text: "Telegram verified", time: "09:21 AM", state: "ok" },
      { type: "ok", text: "Check-in complete", time: "09:28 AM", state: "ok" },
    ],
    services: [
      { name: "HbA1c (Diabetes)", payer: "Direct Pay", status: "paid", amount: 11 },
      { name: "TSH (Thyroid)", payer: "Direct Pay", status: "paid", amount: 14 },
    ],
    cart: {
      items: [
        { id: "hba1c", kind: "lab", name: "HbA1c (Diabetes)", price: 11, qty: 1, payer: "direct", status: "paid" },
        { id: "tsh", kind: "lab", name: "TSH (Thyroid)", price: 14, qty: 1, payer: "direct", status: "paid" },
      ],
      promos: {},
      splits: null,
      ccy: "USD",
      payment: { method: "khqr", status: "confirmed", receiptId: "KUR-260502-043", confirmedAt: "2026-05-02T02:27:30Z", amount: 25, currency: "USD", cashier: "Linh Nguyen" },
      pregnancyConsent: null,
    },
    visitDetails: {
      chiefComplaint: "Diabetes monitoring, no acute symptoms",
      medicalHistory: "Type 2 diabetes",
      medications: "Metformin 500mg twice daily",
      allergies: "None known",
      notes: "Asked for printed receipt.",
    },
    labTests: [
      { id: "hba1c", name: "HbA1c (Diabetes)", price: 11, status: "ordered" },
      { id: "tsh", name: "TSH (Thyroid)", price: 14, status: "ordered" },
    ],
    insurance: [],
    priorResults: [
      { id: "pr-sp1", testId: "hba1c", testName: "HbA1c (Diabetes)", visitDate: "2026-02-12", status: "complete", price: 11, sensitive: true },
      { id: "pr-sp2", testId: "kft", testName: "Kidney Function (KFT)", visitDate: "2026-02-12", status: "complete", price: 13, sensitive: true },
    ],
    teleconsult: { status: "notBooked", slot: null, by: null },
    handoff: 3,
    handoffStates: ["done","done","done","done"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:22 AM",
  },
  {
    id: "p6",
    name: "Dara Kim",
    gender: "Male",
    sexAtBirth: "Male",
    age: 46,
    initials: "DK",
    avatarColor: "av-teal",
    arrivedAt: "09:26 AM",
    queueNumber: "Q-044",
    status: { tone: "warn", label: "Orders needed" },
    visitReason: ["Executive check-up", "Returning patient"],
    language: "English",
    countryCode: "+855",
    phoneNumber: "11 600 300",
    mobile: "+855 11 600 300",
    dob: "1980-01-05",
    telegramHandle: "",
    telegramVerified: false,
    commMethod: "sms",
    otpVerified: true,
    pwaSentAt: "09:24 AM",
    idScanned: true,
    idNumber: "810056003",
    payer: "direct",
    insuranceAcked: true,
    documents: { id: "ok", consent: "ok", insurance: "pending", receipt: "pending" },
    pwaProgress: 100,
    pwaLog: [
      { type: "sent", text: "Link sent by SMS", time: "09:24 AM", state: "ok" },
      { type: "verified", text: "OTP verified", time: "09:25 AM", state: "ok" },
      { type: "ok", text: "Review complete", time: "09:26 AM", state: "ok" },
    ],
    services: [],
    cart: {
      items: [],
      promos: {},
      splits: null,
      ccy: "USD",
      payment: { method: null, status: "idle", tendered: "" },
      pregnancyConsent: null,
    },
    visitDetails: {
      chiefComplaint: "Annual executive check-up",
      medicalHistory: "No chronic illnesses reported",
      medications: "None",
      allergies: "Shellfish",
      notes: "",
    },
    labTests: [],
    insurance: [],
    priorResults: [
      { id: "pr-dk1", testId: "cbc", testName: "Complete Blood Count (CBC)", visitDate: "2025-08-03", status: "complete", price: 8, sensitive: false },
      { id: "pr-dk2", testId: "lipid", testName: "Lipid Panel", visitDate: "2025-08-03", status: "complete", price: 12, sensitive: true },
      { id: "pr-dk3", testId: "lft", testName: "Liver Function (LFT)", visitDate: "2025-08-03", status: "complete", price: 13, sensitive: true },
    ],
    teleconsult: { status: "notBooked", slot: null, by: null },
    handoff: 1,
    handoffStates: ["done","done","done","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:26 AM",
  },
  {
    id: "p7",
    name: "Nary Chea",
    gender: "Female",
    sexAtBirth: "Female",
    age: 33,
    initials: "NC",
    avatarColor: "av-pink",
    arrivedAt: "09:30 AM",
    queueNumber: "Q-045",
    status: { tone: "warn", label: "Verify contact" },
    visitReason: ["Fatigue", "Price estimate"],
    language: "Khmer",
    countryCode: "+855",
    phoneNumber: "92 218 700",
    mobile: "+855 92 218 700",
    dob: "1993-07-21",
    telegramHandle: "",
    telegramVerified: false,
    commMethod: "sms",
    otpVerified: false,
    pwaSentAt: "09:29 AM",
    idScanned: true,
    idNumber: "920218700",
    payer: "direct",
    insuranceAcked: true,
    documents: { id: "ok", consent: "pending", insurance: "pending", receipt: "pending" },
    pwaProgress: 35,
    pwaLog: [
      { type: "sent", text: "Link sent by SMS", time: "09:29 AM", state: "ok" },
      { type: "pending", text: "OTP not verified", time: "Awaiting patient", state: "pending" },
    ],
    services: [
      { name: "Complete Blood Count (CBC)", payer: "Direct Pay", status: "staged", amount: 8 },
      { name: "Ferritin", payer: "Direct Pay", status: "staged", amount: 9 },
    ],
    cart: {
      items: [
        { id: "cbc", kind: "lab", name: "Complete Blood Count (CBC)", price: 8, qty: 1, payer: "direct", status: "pending" },
        { id: "ferritin", kind: "lab", name: "Ferritin", price: 9, qty: 1, payer: "direct", status: "pending" },
      ],
      promos: {},
      splits: null,
      ccy: "USD",
      payment: { method: null, status: "idle", tendered: "" },
      pregnancyConsent: null,
    },
    visitDetails: {
      chiefComplaint: "Fatigue and dizziness for two weeks",
      medicalHistory: "",
      medications: "",
      allergies: "",
      notes: "Patient asked for price before OTP verification.",
    },
    labTests: [],
    insurance: [],
    priorResults: [],
    teleconsult: { status: "notBooked", slot: null, by: null },
    handoff: 0,
    handoffStates: ["done","in-progress","pending","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:30 AM",
  },
  {
    id: "p8",
    name: "Vannak Sok",
    gender: "Male",
    sexAtBirth: "Male",
    age: 39,
    initials: "VS",
    avatarColor: "av-green",
    arrivedAt: "09:33 AM",
    queueNumber: "Q-046",
    status: { tone: "info", label: "Insurance ready" },
    visitReason: ["Chest discomfort", "Insurance billing"],
    language: "Khmer",
    countryCode: "+855",
    phoneNumber: "70 334 112",
    mobile: "+855 70 334 112",
    dob: "1987-12-11",
    telegramHandle: "t.me/vannaksok",
    telegramVerified: true,
    commMethod: "telegram",
    otpVerified: true,
    pwaSentAt: "09:31 AM",
    idScanned: true,
    idNumber: "703341122",
    payer: "insurance",
    insuranceAcked: true,
    documents: { id: "ok", consent: "ok", insurance: "ok", receipt: "pending" },
    pwaProgress: 90,
    pwaLog: [
      { type: "sent", text: "Link sent by Telegram", time: "09:31 AM", state: "ok" },
      { type: "verified", text: "Telegram verified", time: "09:31 AM", state: "ok" },
      { type: "ok", text: "Insurance card matched", time: "09:33 AM", state: "ok" },
    ],
    services: [
      { name: "ECG — 12 lead", payer: "Insurance", status: "pending", amount: 22 },
      { name: "Lipid Panel", payer: "Insurance", status: "pending", amount: 12 },
    ],
    cart: {
      items: [
        { id: "ecg-12", kind: "ecg", name: "ECG — 12 lead", price: 22, qty: 1, payer: "insurance", status: "pending" },
        { id: "lipid", kind: "lab", name: "Lipid Panel", price: 12, qty: 1, payer: "insurance", status: "pending", fasting: true },
      ],
      promos: {},
      splits: null,
      ccy: "USD",
      payment: { method: null, status: "idle", tendered: "" },
      pregnancyConsent: null,
    },
    visitDetails: {
      chiefComplaint: "Mild chest discomfort after exercise",
      medicalHistory: "Family history of hypertension",
      medications: "",
      allergies: "None known",
      notes: "Insurance may partially cover ECG.",
    },
    labTests: [
      { id: "lipid", name: "Lipid Panel", price: 12, status: "pending" },
    ],
    insurance: [
      { id: "ins-vs", provider: "AIA Cambodia", policyNumber: "AIA-883021", memberName: "Vannak Sok", memberId: "AIA-M-20491", expiry: "09/2027", coverage: "Outpatient 80%", cardAttached: true },
    ],
    priorResults: [
      { id: "pr-vs1", testId: "ecg-12", testName: "ECG — 12 lead", visitDate: "2025-11-09", status: "complete", price: 22, sensitive: false },
    ],
    teleconsult: { status: "notBooked", slot: null, by: null },
    handoff: 1,
    handoffStates: ["done","done","done","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:33 AM",
  },
  {
    id: "p9",
    name: "Elise Martin",
    gender: "Female",
    sexAtBirth: "Female",
    age: 29,
    initials: "EM",
    avatarColor: "av-amber",
    arrivedAt: "09:37 AM",
    queueNumber: "Q-047",
    status: { tone: "success", label: "Paid" },
    visitReason: ["Travel clearance", "COVID PCR"],
    language: "English",
    countryCode: "+33",
    phoneNumber: "6 44 18 90 20",
    mobile: "+33 6 44 18 90 20",
    dob: "1997-03-09",
    telegramHandle: "",
    telegramVerified: false,
    commMethod: "sms",
    otpVerified: true,
    pwaSentAt: "09:35 AM",
    idScanned: true,
    idNumber: "FR775901",
    payer: "direct",
    insuranceAcked: true,
    documents: { id: "ok", consent: "ok", insurance: "pending", receipt: "ok" },
    pwaProgress: 100,
    pwaLog: [
      { type: "sent", text: "Link sent by SMS", time: "09:35 AM", state: "ok" },
      { type: "verified", text: "OTP verified", time: "09:36 AM", state: "ok" },
      { type: "ok", text: "Payment confirmed", time: "09:38 AM", state: "ok" },
    ],
    services: [
      { name: "COVID-19 PCR", payer: "Direct Pay", status: "paid", amount: 18 },
    ],
    cart: {
      items: [
        { id: "covid", kind: "lab", name: "COVID-19 PCR", price: 18, qty: 1, payer: "direct", status: "paid" },
      ],
      promos: {},
      splits: null,
      ccy: "USD",
      payment: { method: "cash", status: "confirmed", receiptId: "KUR-260502-047", confirmedAt: "2026-05-02T02:38:00Z", amount: 18, currency: "USD", tendered: "20", change: 2, cashier: "Linh Nguyen" },
      pregnancyConsent: null,
    },
    visitDetails: {
      chiefComplaint: "PCR test required for travel",
      medicalHistory: "",
      medications: "",
      allergies: "",
      notes: "Needs result by evening.",
    },
    labTests: [
      { id: "covid", name: "COVID-19 PCR", price: 18, status: "ordered" },
    ],
    insurance: [],
    priorResults: [],
    teleconsult: { status: "notBooked", slot: null, by: null },
    handoff: 2,
    handoffStates: ["done","done","done","in-progress"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:37 AM",
  },
  {
    id: "p10",
    name: "Chan Rotha",
    gender: "Male",
    sexAtBirth: "Male",
    age: 61,
    initials: "CR",
    avatarColor: "av-blue",
    arrivedAt: "09:40 AM",
    queueNumber: "Q-048",
    status: { tone: "info", label: "Payment pending" },
    visitReason: ["Kidney follow-up", "KHQR waiting"],
    language: "Khmer",
    countryCode: "+855",
    phoneNumber: "15 221 700",
    mobile: "+855 15 221 700",
    dob: "1965-05-30",
    telegramHandle: "",
    telegramVerified: false,
    commMethod: "sms",
    otpVerified: true,
    pwaSentAt: "09:38 AM",
    idScanned: true,
    idNumber: "152217000",
    payer: "direct",
    insuranceAcked: true,
    documents: { id: "ok", consent: "ok", insurance: "pending", receipt: "pending" },
    pwaProgress: 100,
    pwaLog: [
      { type: "sent", text: "Link sent by SMS", time: "09:38 AM", state: "ok" },
      { type: "verified", text: "OTP verified", time: "09:39 AM", state: "ok" },
      { type: "pending", text: "KHQR waiting", time: "09:40 AM", state: "pending" },
    ],
    services: [
      { name: "Kidney Function (KFT)", payer: "Direct Pay", status: "payment waiting", amount: 13 },
      { name: "Urinalysis", payer: "Direct Pay", status: "payment waiting", amount: 6 },
    ],
    cart: {
      items: [
        { id: "kft", kind: "lab", name: "Kidney Function (KFT)", price: 13, qty: 1, payer: "direct", status: "pending" },
        { id: "urinalysis", kind: "lab", name: "Urinalysis", price: 6, qty: 1, payer: "direct", status: "pending" },
      ],
      promos: {},
      splits: null,
      ccy: "USD",
      payment: { method: "khqr", status: "waiting", tendered: "" },
      pregnancyConsent: null,
    },
    visitDetails: {
      chiefComplaint: "Follow-up for kidney function",
      medicalHistory: "Hypertension",
      medications: "Amlodipine",
      allergies: "",
      notes: "",
    },
    labTests: [],
    insurance: [],
    priorResults: [
      { id: "pr-cr1", testId: "kft", testName: "Kidney Function (KFT)", visitDate: "2026-03-01", status: "complete", price: 13, sensitive: true },
    ],
    teleconsult: { status: "notBooked", slot: null, by: null },
    handoff: 1,
    handoffStates: ["done","done","done","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:40 AM",
  },
  {
    id: "p11",
    name: "Srey Mom",
    gender: "Female",
    sexAtBirth: "Female",
    age: 24,
    initials: "SM",
    avatarColor: "av-purple",
    arrivedAt: "09:43 AM",
    queueNumber: "Q-049",
    status: { tone: "danger", label: "Consent required" },
    visitReason: ["Ankle injury", "Imaging consent"],
    language: "Khmer",
    countryCode: "+855",
    phoneNumber: "96 410 021",
    mobile: "+855 96 410 021",
    dob: "2002-02-02",
    telegramHandle: "t.me/sreymom",
    telegramVerified: true,
    commMethod: "telegram",
    otpVerified: true,
    pwaSentAt: "09:41 AM",
    idScanned: true,
    idNumber: "964100210",
    payer: "direct",
    insuranceAcked: true,
    documents: { id: "ok", consent: "pending", insurance: "pending", receipt: "pending" },
    pwaProgress: 85,
    pwaLog: [
      { type: "sent", text: "Link sent by Telegram", time: "09:41 AM", state: "ok" },
      { type: "verified", text: "Telegram verified", time: "09:42 AM", state: "ok" },
      { type: "danger", text: "Imaging consent pending", time: "Blocking payment", state: "danger" },
    ],
    services: [
      { name: "X-ray — Ankle", payer: "Direct Pay", status: "consent pending", amount: 15 },
    ],
    cart: {
      items: [
        { id: "xray-ankle", kind: "imaging", name: "X-ray — Ankle", price: 15, qty: 1, payer: "direct", status: "pending", validationState: "sent" },
      ],
      promos: {},
      splits: null,
      ccy: "USD",
      payment: { method: null, status: "idle", tendered: "" },
      pregnancyConsent: null,
    },
    visitDetails: {
      chiefComplaint: "Ankle pain after fall",
      medicalHistory: "",
      medications: "",
      allergies: "",
      notes: "Pregnancy screening required before imaging.",
    },
    labTests: [],
    insurance: [],
    priorResults: [],
    teleconsult: { status: "notBooked", slot: null, by: null },
    handoff: 1,
    handoffStates: ["done","done","done","blocked"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:43 AM",
    exception: "consent",
  },
  {
    id: "p12",
    name: "Ahmed Khan",
    gender: "Male",
    sexAtBirth: "Male",
    age: 41,
    initials: "AK",
    avatarColor: "av-teal",
    arrivedAt: "09:47 AM",
    queueNumber: "Q-050",
    status: { tone: "info", label: "Awaiting ID" },
    visitReason: ["Booking follow-up", "VID search case"],
    language: "English",
    countryCode: "+971",
    phoneNumber: "50 902 1144",
    mobile: "+971 50 902 1144",
    dob: "1985-10-18",
    telegramHandle: "",
    telegramVerified: false,
    commMethod: "sms",
    otpVerified: false,
    pwaSentAt: null,
    idScanned: false,
    idNumber: "VID-260502-050",
    payer: "direct",
    insuranceAcked: false,
    documents: { id: "pending", consent: "pending", insurance: "pending", receipt: "pending" },
    pwaProgress: 0,
    pwaLog: [
      { type: "pending", text: "Waiting for National ID scan", time: "Now", state: "pending" },
    ],
    services: [],
    cart: {
      items: [],
      promos: {},
      splits: null,
      ccy: "USD",
      payment: { method: null, status: "idle", tendered: "" },
      pregnancyConsent: null,
    },
    visitDetails: {
      chiefComplaint: "",
      medicalHistory: "",
      medications: "",
      allergies: "",
      notes: "Walk-in created from booking desk; ID not captured yet.",
    },
    labTests: [],
    insurance: [],
    priorResults: [
      { id: "pr-ak1", testId: "covid", testName: "COVID-19 PCR", visitDate: "2025-06-18", status: "complete", price: 18, sensitive: false },
    ],
    teleconsult: { status: "notBooked", slot: null, by: null },
    handoff: 0,
    handoffStates: ["in-progress","pending","pending","pending"],
    identity: { verified: false },
    arrivedRaw: "Today, 09:47 AM",
    manualEntry: true,
  },
];

export const queueCounts = { Waiting: 12, "Intake Sent": 7, Ready: 5, Exceptions: 4 };

export const initialNotifications = [
  {
    id: "n1",
    tone: "danger",
    icon: "AlertTriangle",
    titleKey: "notif.consentDeclined",
    bodyKey: "notif.consentDeclined.body",
    bodyParams: { name: "An Le" },
    time: "2m ago",
    timeKey: "time.minutesAgo",
    timeParams: { n: 2 },
    read: false,
    patientId: "p4",
    actionKey: "notif.action.review",
  },
  {
    id: "n2",
    tone: "warn",
    icon: "Shield",
    titleKey: "notif.insurancePending",
    bodyKey: "notif.insurancePending.body",
    bodyParams: { name: "Bao Nguyen" },
    time: "8m ago",
    timeKey: "time.minutesAgo",
    timeParams: { n: 8 },
    read: false,
    patientId: "p2",
    actionKey: "notif.action.verify",
  },
  {
    id: "n3",
    tone: "info",
    icon: "Smartphone",
    titleKey: "notif.pwaCompleted",
    bodyKey: "notif.pwaCompleted.body",
    bodyParams: { name: "Pierre Tison" },
    time: "12m ago",
    timeKey: "time.minutesAgo",
    timeParams: { n: 12 },
    read: false,
    patientId: "p3",
    actionKey: "notif.action.open",
  },
  {
    id: "n4",
    tone: "success",
    icon: "Flask",
    titleKey: "notif.labReady",
    bodyKey: "notif.labReady.body",
    bodyParams: { name: "Sokha Pich" },
    time: "23m ago",
    timeKey: "time.minutesAgo",
    timeParams: { n: 23 },
    read: true,
    actionKey: "notif.action.view",
  },
  {
    id: "n5",
    tone: "info",
    icon: "Calendar",
    titleKey: "notif.appointmentReminder",
    bodyKey: "notif.appointmentReminder.body",
    bodyParams: { count: 5 },
    time: "1h ago",
    timeKey: "time.hoursAgo",
    timeParams: { n: 1 },
    read: true,
    actionKey: "notif.action.viewSchedule",
  },
  {
    id: "n6",
    tone: "info",
    icon: "Settings",
    titleKey: "notif.systemUpdate",
    bodyKey: "notif.systemUpdate.body",
    time: "2h ago",
    timeKey: "time.hoursAgo",
    timeParams: { n: 2 },
    read: true,
    actionKey: "notif.action.learnMore",
  },
];

export const stations = [
  { id: "PSC-01", labelKey: "station.psc01", caption: "Main reception" },
  { id: "PSC-02", labelKey: "station.psc02", caption: "Triage desk" },
  { id: "PSC-03", labelKey: "station.psc03", caption: "Express counter" },
];

export const shifts = [
  { id: "morning", labelKey: "topbar.shiftMorning", time: "07:00 — 13:00" },
  { id: "afternoon", labelKey: "shift.afternoon", time: "13:00 — 19:00" },
  { id: "night", labelKey: "shift.night", time: "19:00 — 23:00" },
];

export const payerOptions = [
  { id: "direct",    name: "Direct Pay", icon: "CreditCard", caption: "Patient pays at counter" },
  { id: "insurance", name: "Insurance",  icon: "Shield",      caption: "Verify insurance card" },
  { id: "corporate", name: "Corporate",  icon: "Building",    caption: "Bill to employer" },
  { id: "referral",  name: "Referral",   icon: "Network",     caption: "Linked to referring clinic" },
];

export const LAB_CATALOG = [
  { id: "cbc",          name: "Complete Blood Count (CBC)", category: "Haematology", popular: true,  price: 8 },
  { id: "glucose",      name: "Blood Glucose (Fasting)",    category: "Biochemistry", popular: true, price: 5 },
  { id: "lipid",        name: "Lipid Panel",                category: "Biochemistry", popular: true, price: 12 },
  { id: "tsh",          name: "TSH (Thyroid)",              category: "Biochemistry", popular: true, price: 14 },
  { id: "urinalysis",   name: "Urinalysis",                 category: "Urinalysis",   popular: true, price: 6 },
  { id: "preg",         name: "Pregnancy (β-hCG)",          category: "Biochemistry", popular: true, price: 7 },
  { id: "hba1c",        name: "HbA1c (Diabetes)",           category: "Biochemistry", price: 11 },
  { id: "lft",          name: "Liver Function (LFT)",       category: "Biochemistry", price: 13 },
  { id: "kft",          name: "Kidney Function (KFT)",      category: "Biochemistry", price: 13 },
  { id: "electro",      name: "Electrolytes Panel",         category: "Biochemistry", price: 9 },
  { id: "esr",          name: "ESR (Sed Rate)",             category: "Haematology",  price: 5 },
  { id: "ferritin",     name: "Ferritin",                   category: "Haematology",  price: 9 },
  { id: "ptinr",        name: "PT / INR",                   category: "Haematology",  price: 8 },
  { id: "strep",        name: "Strep Throat Culture",       category: "Microbiology", price: 10 },
  { id: "covid",        name: "COVID-19 PCR",               category: "Microbiology", price: 18 },
  { id: "stool",        name: "Stool Culture",              category: "Microbiology", price: 11 },
  { id: "hiv",          name: "HIV Antibody",               category: "Immunology",   price: 12 },
  { id: "hep",          name: "Hepatitis B Surface Ag",     category: "Immunology",   price: 10 },
  { id: "ana",          name: "ANA (Autoimmune Screen)",    category: "Immunology",   price: 16 },
  { id: "urineculture", name: "Urine Culture & Sensitivity",category: "Urinalysis",   price: 9 },
  { id: "microalbumin", name: "Urine Microalbumin",         category: "Urinalysis",   price: 7 },
];

export const LAB_CATEGORIES = ["Popular", "Biochemistry", "Haematology", "Microbiology", "Immunology", "Urinalysis"];

export const INSURANCE_PROVIDERS = [
  "Forte Insurance",
  "Prudential",
  "AIA Cambodia",
  "Manulife",
  "Cambodia Life Insurance",
  "Sovannaphum Life",
  "Asia Insurance",
  "Infinity General Insurance",
  "NSSF (National Social Security Fund)",
  "Bupa Global",
  "Pacific Cross",
];

export const VISIT_FEE = 15;
export const KHR_RATE = 4100;
