// === Kura Reception — seed data ===

export const initialPatients = [
  {
    id: "p1",
    name: "Maya Tran",
    gender: "Female",
    sexAtBirth: "Female",
    age: 28,
    initials: "MT",
    avatarColor: "av-blue",
    arrivedAt: "09:12 AM",
    queueNumber: "Q-042",
    status: { tone: "info", label: "PWA sent" },
    visitReason: ["General check-up"],
    language: "English",
    countryCode: "+855",
    phoneNumber: "12 345 678",
    mobile: "+855 12 345 678",
    dob: "1996-02-14",
    telegramHandle: "t.me/mayatran",
    commMethod: "telegram",
    otpVerified: true,
    pwaSentAt: "09:12 AM",
    idScanned: true,
    idNumber: "012345678",
    payer: "direct",
    documents: { id: "ok", consent: "ok", insurance: "pending", receipt: "pending" },
    pwaProgress: 62,
    pwaLog: [
      { type: "sent",      text: "Link sent by SMS",         time: "09:12 AM", state: "ok" },
      { type: "verified",  text: "OTP verified",             time: "09:13 AM", state: "ok" },
      { type: "pending",   text: "Medical history pending",  time: "62% complete", state: "pending" },
    ],
    services: [
      { name: "CBC",            payer: "Direct Pay", status: "draft", amount: 6 },
      { name: "Glucose Fasting",payer: "Direct Pay", status: "draft", amount: 3 },
      { name: "Vitamin D",      payer: "Direct Pay", status: "draft", amount: 25 },
      { name: "X-ray Chest",    payer: "Direct Pay", status: "draft", amount: 15 },
    ],
    visitDetails: {
      chiefComplaint: "Headache and mild fever for 3 days",
      medicalHistory: "Hypertension (controlled), no surgeries",
      medications: "Lisinopril 10mg daily",
      allergies: "Penicillin",
      notes: "",
    },
    labTests: [
      { id: "cbc",     name: "Complete Blood Count (CBC)", price: 8, status: "in-progress" },
      { id: "glucose", name: "Blood Glucose (Fasting)",    price: 5, status: "pending" },
    ],
    insurance: [],
    handoff: 1,
    handoffStates: ["new","in-progress","pending","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:12 AM",
  },
  {
    id: "p2",
    name: "Bao Nguyen",
    gender: "Male",
    sexAtBirth: "Male",
    age: 35,
    initials: "BN",
    avatarColor: "av-green",
    arrivedAt: "09:05 AM",
    queueNumber: "Q-041",
    status: { tone: "warn", label: "Needs insurance" },
    visitReason: ["Annual physical"],
    language: "Vietnamese",
    countryCode: "+84",
    phoneNumber: "933 222 110",
    mobile: "+84 933 222 110",
    dob: "1989-06-03",
    telegramHandle: "",
    commMethod: "sms",
    otpVerified: true,
    pwaSentAt: "09:05 AM",
    idScanned: true,
    idNumber: "445566778",
    payer: "insurance",
    documents: { id: "ok", consent: "ok", insurance: "pending", receipt: "pending" },
    pwaProgress: 80,
    pwaLog: [
      { type: "sent",     text: "Link sent by SMS",        time: "09:05 AM", state: "ok" },
      { type: "verified", text: "OTP verified",            time: "09:06 AM", state: "ok" },
      { type: "warn",     text: "Insurance card not uploaded", time: "Awaiting", state: "warn" },
    ],
    services: [
      { name: "Lipid Panel", payer: "Insurance",  status: "pending", amount: 12 },
      { name: "ECG",         payer: "Insurance",  status: "pending", amount: 22 },
    ],
    visitDetails: {
      chiefComplaint: "Routine annual physical",
      medicalHistory: "",
      medications: "",
      allergies: "None known",
      notes: "",
    },
    labTests: [
      { id: "lipid", name: "Lipid Panel", price: 12, status: "pending" },
    ],
    insurance: [
      { id: "ins-p2", provider: "Forte Insurance", policyNumber: "FT-00123456", memberName: "Bao Nguyen", memberId: "M-7788991", expiry: "12/2026", coverage: "Outpatient", cardAttached: false },
    ],
    handoff: 1,
    handoffStates: ["done","in-progress","pending","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:05 AM",
  },
  {
    id: "p3",
    name: "Pierre Tison",
    gender: "Male",
    sexAtBirth: "Male",
    age: 31,
    initials: "PT",
    avatarColor: "av-amber",
    arrivedAt: "08:58 AM",
    queueNumber: "Q-040",
    status: { tone: "success", label: "Ready for nurse" },
    visitReason: ["Follow-up"],
    language: "English",
    countryCode: "+855",
    phoneNumber: "77 555 244",
    mobile: "+855 77 555 244",
    dob: "1993-11-22",
    telegramHandle: "t.me/pierret",
    commMethod: "telegram",
    otpVerified: true,
    pwaSentAt: "08:58 AM",
    idScanned: true,
    idNumber: "998877665",
    payer: "corporate",
    documents: { id: "ok", consent: "ok", insurance: "ok", receipt: "ok" },
    pwaProgress: 100,
    pwaLog: [
      { type: "sent",     text: "Link sent by SMS",      time: "08:58 AM", state: "ok" },
      { type: "verified", text: "OTP verified",          time: "08:59 AM", state: "ok" },
      { type: "ok",       text: "Medical history complete", time: "09:04 AM", state: "ok" },
    ],
    services: [
      { name: "Blood Pressure",  payer: "Corporate", status: "ready", amount: 0 },
      { name: "Vision Test",     payer: "Corporate", status: "ready", amount: 0 },
    ],
    visitDetails: {
      chiefComplaint: "Follow-up after lipid results last visit",
      medicalHistory: "Borderline cholesterol",
      medications: "None",
      allergies: "None",
      notes: "Patient reports diet changes are working.",
    },
    labTests: [
      { id: "hba1c", name: "HbA1c (Diabetes)", price: 11, status: "complete" },
      { id: "lipid", name: "Lipid Panel",      price: 12, status: "complete" },
    ],
    insurance: [],
    handoff: 2,
    handoffStates: ["done","done","in-progress","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 08:58 AM",
  },
  {
    id: "p4",
    name: "An Le",
    gender: "Female",
    sexAtBirth: "Female",
    age: 42,
    initials: "AL",
    avatarColor: "av-pink",
    arrivedAt: "08:45 AM",
    queueNumber: "Q-039",
    status: { tone: "danger", label: "Missing consent" },
    visitReason: ["X-ray follow-up"],
    language: "Vietnamese",
    countryCode: "+855",
    phoneNumber: "88 102 909",
    mobile: "+855 88 102 909",
    dob: "1982-04-30",
    telegramHandle: "",
    commMethod: "sms",
    otpVerified: false,
    idScanned: true,
    idNumber: "112233445",
    payer: "direct",
    documents: { id: "ok", consent: "pending", insurance: "pending", receipt: "pending" },
    pwaProgress: 45,
    pwaLog: [
      { type: "sent",     text: "Link sent by SMS",  time: "08:45 AM", state: "ok" },
      { type: "verified", text: "OTP verified",      time: "08:46 AM", state: "ok" },
      { type: "danger",   text: "Consent declined — needs counter signature", time: "Blocking", state: "danger" },
    ],
    services: [
      { name: "X-ray Lumbar", payer: "Direct Pay", status: "blocked", amount: 18 },
    ],
    visitDetails: {
      chiefComplaint: "",
      medicalHistory: "",
      medications: "",
      allergies: "",
      notes: "",
    },
    labTests: [],
    insurance: [],
    handoff: 0,
    handoffStates: ["in-progress","blocked","pending","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 08:45 AM",
    exception: "consent",
  },
];

export const queueCounts = { Waiting: 4, "Intake Sent": 3, Ready: 2, Exceptions: 2 };

export const initialNotifications = [
  {
    id: "n1",
    tone: "danger",
    icon: "AlertTriangle",
    titleKey: "notif.consentDeclined",
    bodyKey: "notif.consentDeclined.body",
    bodyParams: { name: "An Le" },
    time: "2m ago",
    timeKey: "time.minutesAgo",
    timeParams: { n: 2 },
    read: false,
    patientId: "p4",
    actionKey: "notif.action.review",
  },
  {
    id: "n2",
    tone: "warn",
    icon: "Shield",
    titleKey: "notif.insurancePending",
    bodyKey: "notif.insurancePending.body",
    bodyParams: { name: "Bao Nguyen" },
    time: "8m ago",
    timeKey: "time.minutesAgo",
    timeParams: { n: 8 },
    read: false,
    patientId: "p2",
    actionKey: "notif.action.verify",
  },
  {
    id: "n3",
    tone: "info",
    icon: "Smartphone",
    titleKey: "notif.pwaCompleted",
    bodyKey: "notif.pwaCompleted.body",
    bodyParams: { name: "Pierre Tison" },
    time: "12m ago",
    timeKey: "time.minutesAgo",
    timeParams: { n: 12 },
    read: false,
    patientId: "p3",
    actionKey: "notif.action.open",
  },
  {
    id: "n4",
    tone: "success",
    icon: "Flask",
    titleKey: "notif.labReady",
    bodyKey: "notif.labReady.body",
    bodyParams: { name: "Sokha Pich" },
    time: "23m ago",
    timeKey: "time.minutesAgo",
    timeParams: { n: 23 },
    read: true,
    actionKey: "notif.action.view",
  },
  {
    id: "n5",
    tone: "info",
    icon: "Calendar",
    titleKey: "notif.appointmentReminder",
    bodyKey: "notif.appointmentReminder.body",
    bodyParams: { count: 5 },
    time: "1h ago",
    timeKey: "time.hoursAgo",
    timeParams: { n: 1 },
    read: true,
    actionKey: "notif.action.viewSchedule",
  },
  {
    id: "n6",
    tone: "info",
    icon: "Settings",
    titleKey: "notif.systemUpdate",
    bodyKey: "notif.systemUpdate.body",
    time: "2h ago",
    timeKey: "time.hoursAgo",
    timeParams: { n: 2 },
    read: true,
    actionKey: "notif.action.learnMore",
  },
];

export const stations = [
  { id: "PSC-01", labelKey: "station.psc01", caption: "Main reception" },
  { id: "PSC-02", labelKey: "station.psc02", caption: "Triage desk" },
  { id: "PSC-03", labelKey: "station.psc03", caption: "Express counter" },
];

export const shifts = [
  { id: "morning", labelKey: "topbar.shiftMorning", time: "07:00 — 13:00" },
  { id: "afternoon", labelKey: "shift.afternoon", time: "13:00 — 19:00" },
  { id: "night", labelKey: "shift.night", time: "19:00 — 23:00" },
];

export const payerOptions = [
  { id: "direct",    name: "Direct Pay", icon: "CreditCard", caption: "Patient pays at counter" },
  { id: "insurance", name: "Insurance",  icon: "Shield",      caption: "Verify insurance card" },
  { id: "corporate", name: "Corporate",  icon: "Building",    caption: "Bill to employer" },
  { id: "referral",  name: "Referral",   icon: "Network",     caption: "Linked to referring clinic" },
];

export const LAB_CATALOG = [
  { id: "cbc",          name: "Complete Blood Count (CBC)", category: "Haematology", popular: true,  price: 8 },
  { id: "glucose",      name: "Blood Glucose (Fasting)",    category: "Biochemistry", popular: true, price: 5 },
  { id: "lipid",        name: "Lipid Panel",                category: "Biochemistry", popular: true, price: 12 },
  { id: "tsh",          name: "TSH (Thyroid)",              category: "Biochemistry", popular: true, price: 14 },
  { id: "urinalysis",   name: "Urinalysis",                 category: "Urinalysis",   popular: true, price: 6 },
  { id: "preg",         name: "Pregnancy (β-hCG)",          category: "Biochemistry", popular: true, price: 7 },
  { id: "hba1c",        name: "HbA1c (Diabetes)",           category: "Biochemistry", price: 11 },
  { id: "lft",          name: "Liver Function (LFT)",       category: "Biochemistry", price: 13 },
  { id: "kft",          name: "Kidney Function (KFT)",      category: "Biochemistry", price: 13 },
  { id: "electro",      name: "Electrolytes Panel",         category: "Biochemistry", price: 9 },
  { id: "esr",          name: "ESR (Sed Rate)",             category: "Haematology",  price: 5 },
  { id: "ferritin",     name: "Ferritin",                   category: "Haematology",  price: 9 },
  { id: "ptinr",        name: "PT / INR",                   category: "Haematology",  price: 8 },
  { id: "strep",        name: "Strep Throat Culture",       category: "Microbiology", price: 10 },
  { id: "covid",        name: "COVID-19 PCR",               category: "Microbiology", price: 18 },
  { id: "stool",        name: "Stool Culture",              category: "Microbiology", price: 11 },
  { id: "hiv",          name: "HIV Antibody",               category: "Immunology",   price: 12 },
  { id: "hep",          name: "Hepatitis B Surface Ag",     category: "Immunology",   price: 10 },
  { id: "ana",          name: "ANA (Autoimmune Screen)",    category: "Immunology",   price: 16 },
  { id: "urineculture", name: "Urine Culture & Sensitivity",category: "Urinalysis",   price: 9 },
  { id: "microalbumin", name: "Urine Microalbumin",         category: "Urinalysis",   price: 7 },
];

export const LAB_CATEGORIES = ["Popular", "Biochemistry", "Haematology", "Microbiology", "Immunology", "Urinalysis"];

export const INSURANCE_PROVIDERS = [
  "Forte Insurance",
  "Prudential",
  "AIA Cambodia",
  "Manulife",
  "Cambodia Life Insurance",
  "Sovannaphum Life",
  "Asia Insurance",
  "Infinity General Insurance",
  "NSSF (National Social Security Fund)",
  "Bupa Global",
  "Pacific Cross",
];

export const VISIT_FEE = 15;
export const KHR_RATE = 4100;
