// === Kura Reception — seed data ===

export const initialPatients = [
  {
    id: "p1",
    name: "Maya Tran",
    gender: "Female",
    sexAtBirth: "Female",
    age: 28,
    initials: "MT",
    avatarColor: "av-blue",
    arrivedAt: "09:12 AM",
    queueNumber: "Q-042",
    status: { tone: "info", label: "PWA sent" },
    visitReason: ["General check-up"],
    language: "English",
    countryCode: "+855",
    phoneNumber: "12 345 678",
    mobile: "+855 12 345 678",
    dob: "1996-02-14",
    telegramHandle: "t.me/mayatran",
    idScanned: true,
    idNumber: "012345678",
    payer: "direct",
    documents: { id: "ok", consent: "ok", insurance: "pending", receipt: "pending" },
    pwaProgress: 62,
    pwaLog: [
      { type: "sent",      text: "Link sent by SMS",         time: "09:12 AM", state: "ok" },
      { type: "verified",  text: "OTP verified",             time: "09:13 AM", state: "ok" },
      { type: "pending",   text: "Medical history pending",  time: "62% complete", state: "pending" },
    ],
    services: [
      { name: "CBC",            payer: "Direct Pay", status: "draft", amount: 6 },
      { name: "Glucose Fasting",payer: "Direct Pay", status: "draft", amount: 3 },
      { name: "Vitamin D",      payer: "Direct Pay", status: "draft", amount: 25 },
      { name: "X-ray Chest",    payer: "Direct Pay", status: "draft", amount: 15 },
    ],
    handoff: 1,
    handoffStates: ["new","in-progress","pending","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:12 AM",
  },
  {
    id: "p2",
    name: "Bao Nguyen",
    gender: "Male",
    sexAtBirth: "Male",
    age: 35,
    initials: "BN",
    avatarColor: "av-green",
    arrivedAt: "09:05 AM",
    queueNumber: "Q-041",
    status: { tone: "warn", label: "Needs insurance" },
    visitReason: ["Annual physical"],
    language: "Vietnamese",
    countryCode: "+84",
    phoneNumber: "933 222 110",
    mobile: "+84 933 222 110",
    dob: "1989-06-03",
    telegramHandle: "",
    idScanned: true,
    idNumber: "445566778",
    payer: "insurance",
    documents: { id: "ok", consent: "ok", insurance: "pending", receipt: "pending" },
    pwaProgress: 80,
    pwaLog: [
      { type: "sent",     text: "Link sent by SMS",        time: "09:05 AM", state: "ok" },
      { type: "verified", text: "OTP verified",            time: "09:06 AM", state: "ok" },
      { type: "warn",     text: "Insurance card not uploaded", time: "Awaiting", state: "warn" },
    ],
    services: [
      { name: "Lipid Panel", payer: "Insurance",  status: "pending", amount: 12 },
      { name: "ECG",         payer: "Insurance",  status: "pending", amount: 22 },
    ],
    handoff: 1,
    handoffStates: ["done","in-progress","pending","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 09:05 AM",
  },
  {
    id: "p3",
    name: "Pierre Tison",
    gender: "Male",
    sexAtBirth: "Male",
    age: 31,
    initials: "PT",
    avatarColor: "av-amber",
    arrivedAt: "08:58 AM",
    queueNumber: "Q-040",
    status: { tone: "success", label: "Ready for nurse" },
    visitReason: ["Follow-up"],
    language: "English",
    countryCode: "+855",
    phoneNumber: "77 555 244",
    mobile: "+855 77 555 244",
    dob: "1993-11-22",
    telegramHandle: "t.me/pierret",
    idScanned: true,
    idNumber: "998877665",
    payer: "corporate",
    documents: { id: "ok", consent: "ok", insurance: "ok", receipt: "ok" },
    pwaProgress: 100,
    pwaLog: [
      { type: "sent",     text: "Link sent by SMS",      time: "08:58 AM", state: "ok" },
      { type: "verified", text: "OTP verified",          time: "08:59 AM", state: "ok" },
      { type: "ok",       text: "Medical history complete", time: "09:04 AM", state: "ok" },
    ],
    services: [
      { name: "Blood Pressure",  payer: "Corporate", status: "ready", amount: 0 },
      { name: "Vision Test",     payer: "Corporate", status: "ready", amount: 0 },
    ],
    handoff: 2,
    handoffStates: ["done","done","in-progress","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 08:58 AM",
  },
  {
    id: "p4",
    name: "An Le",
    gender: "Female",
    sexAtBirth: "Female",
    age: 42,
    initials: "AL",
    avatarColor: "av-pink",
    arrivedAt: "08:45 AM",
    queueNumber: "Q-039",
    status: { tone: "danger", label: "Missing consent" },
    visitReason: ["X-ray follow-up"],
    language: "Vietnamese",
    countryCode: "+855",
    phoneNumber: "88 102 909",
    mobile: "+855 88 102 909",
    dob: "1982-04-30",
    telegramHandle: "",
    idScanned: true,
    idNumber: "112233445",
    payer: "direct",
    documents: { id: "ok", consent: "pending", insurance: "pending", receipt: "pending" },
    pwaProgress: 45,
    pwaLog: [
      { type: "sent",     text: "Link sent by SMS",  time: "08:45 AM", state: "ok" },
      { type: "verified", text: "OTP verified",      time: "08:46 AM", state: "ok" },
      { type: "danger",   text: "Consent declined — needs counter signature", time: "Blocking", state: "danger" },
    ],
    services: [
      { name: "X-ray Lumbar", payer: "Direct Pay", status: "blocked", amount: 18 },
    ],
    handoff: 0,
    handoffStates: ["in-progress","blocked","pending","pending"],
    identity: { verified: true },
    arrivedRaw: "Today, 08:45 AM",
    exception: "consent",
  },
];

export const queueCounts = { Waiting: 4, "Intake Sent": 3, Ready: 2, Exceptions: 2 };

export const payerOptions = [
  { id: "direct",    name: "Direct Pay", icon: "CreditCard", caption: "Patient pays at counter" },
  { id: "insurance", name: "Insurance",  icon: "Shield",      caption: "Verify insurance card" },
  { id: "corporate", name: "Corporate",  icon: "Building",    caption: "Bill to employer" },
  { id: "referral",  name: "Referral",   icon: "Network",     caption: "Linked to referring clinic" },
];
